/**
 * Action: Create Missing PRD
 *
 * Automatically creates a stub PRD file from task metadata
 * when a PRD file is missing for a task.
 */

import fs from 'fs'
import path from 'path'
import { logger } from '../../core/utils'
import type { MonitorAction } from '../types'

export interface CreatePRDOptions {
  tasksFile: string
  prdDirectory: string
}

export async function executeCreatePRD(match: RegExpMatchArray, options: CreatePRDOptions): Promise<void> {
  const taskId = match[1]
  const prdPath = path.join(options.prdDirectory, `${taskId}.md`)

  try {
    // Check if PRD already exists
    if (fs.existsSync(prdPath)) {
      logger.warn(`PRD already exists: ${prdPath}`)
      return
    }

    // Ensure PRD directory exists
    const prdDir = path.dirname(prdPath)
    if (!fs.existsSync(prdDir)) {
      fs.mkdirSync(prdDir, { recursive: true })
    }

    // Create stub PRD from task metadata
    const prdContent = `# ${taskId}

## Goal
Auto-generated PRD - task description was missing or incomplete.

## Requirements
- Review the task context from execution logs
- Add specific requirements and success criteria
- Ensure the task has clear acceptance criteria

## Notes
This PRD was auto-generated by the AI Monitor.
Please review and update with proper task description before execution.

---

**Auto-created by: AI Monitor**
**Reason: PRD file not found**

---

## Context from Execution Logs

*(Task execution attempted but PRD was missing. Review logs for what was attempted and what was needed.)*

`

    fs.writeFileSync(prdPath, prdContent, 'utf-8')
    logger.info(`Created missing PRD: ${prdPath}`)

    // Update tasks.json if it exists
    await updateTaskDescription(taskId, prdContent, options.tasksFile)
  } catch (error) {
    logger.error(`Failed to create PRD for ${taskId}: ${error}`)
    throw error
  }
}

/**
 * Update task description in tasks.json
 */
async function updateTaskDescription(
  taskId: string,
  description: string,
  tasksFile: string
): Promise<void> {
  try {
    if (!fs.existsSync(tasksFile)) {
      return
    }

    const tasksData = JSON.parse(fs.readFileSync(tasksFile, 'utf-8'))
    const taskEntry = tasksData.tasks?.find((t: any) => t.id === taskId)

    if (taskEntry && !taskEntry.description) {
      taskEntry.description = description
      fs.writeFileSync(tasksFile, JSON.stringify(tasksData, null, 2), 'utf-8')
      logger.info(`Updated task description in ${tasksFile}`)
    }
  } catch (error) {
    logger.debug(`Failed to update task description: ${error}`)
  }
}

/**
 * Factory function to create the action
 */
export function createActionCreatePRD(options: CreatePRDOptions): MonitorAction {
  return {
    type: 'auto-fix',
    fn: async () => {
      // This is called by PatternDetector
      // The actual match context is passed via the pattern's autoAction
      throw new Error('Use PatternDetector.detect() which passes matches to this function')
    }
  }
}

/**
 * Execute action directly (used by PatternDetector)
 */
export async function execute(
  match: RegExpMatchArray,
  options: CreatePRDOptions
): Promise<void> {
  return executeCreatePRD(match, options)
}
