/**
 * Auto-create missing PRD files
 *
 * When a task is started but its PRD file doesn't exist,
 * this action generates a stub PRD with a basic template.
 */

import fs from 'fs'
import path from 'path'
import { logger } from '../../core/utils'
import type { Action } from './index'

export interface CreatePRDContext {
  taskId: string
  title?: string
  path?: string
}

/**
 * Extract task ID from PRD not found error message
 */
export function extractTaskInfo(context: Record<string, string>): CreatePRDContext | null {
  const prdPath = context.path

  if (!prdPath) {
    logger.debug('No PRD path found in context')
    return null
  }

  // Extract task ID from path: .specs/tasks/TASK-001.md -> TASK-001
  const match = prdPath.match(/([A-Z]+-\d+[a-z]?)\.md$/i)
  if (!match) {
    logger.debug(`Could not extract task ID from path: ${prdPath}`)
    return null
  }

  const taskId = match[1]
  return {
    taskId,
    path: prdPath
  }
}

/**
 * Generate PRD template content
 */
export function generatePRDTemplate(taskId: string, title?: string): string {
  const taskTitle = title || taskId

  return `# ${taskId}: ${taskTitle}

## Goal
[Auto-generated stub - please fill in requirements]

This PRD was automatically created by AI Monitor when the task was started
without an existing specification file.

## Requirements
- [ ] Define specific requirements
- [ ] Add acceptance criteria
- [ ] Specify constraints or dependencies

## Implementation Notes
Please review and update this PRD with:
- Clear, measurable requirements
- Expected outcomes
- Any technical constraints
- Dependencies on other tasks

## References
- Related tasks: (list any related task IDs)
- Documentation: (links to relevant docs)

---
*Auto-generated by Loopwork AI Monitor*
`
}

/**
 * Create PRD file at specified path
 */
export async function createPRDFile(filePath: string, content: string): Promise<void> {
  const dir = path.dirname(filePath)

  // Create directory if it doesn't exist
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
    logger.debug(`Created directory: ${dir}`)
  }

  // Write PRD file
  fs.writeFileSync(filePath, content, 'utf8')
  logger.debug(`Created PRD file: ${filePath}`)
}

/**
 * Execute auto-create PRD action
 */
export async function executeCreatePRD(action: Action): Promise<void> {
  const taskInfo = extractTaskInfo(action.context)

  if (!taskInfo) {
    throw new Error('Could not extract task information from error context')
  }

  const { taskId, path: prdPath } = taskInfo

  // Determine PRD file path
  const filePath = prdPath || path.join(process.cwd(), '.specs', 'tasks', `${taskId}.md`)

  // Check if file already exists (race condition protection)
  if (fs.existsSync(filePath)) {
    logger.info(`PRD file already exists: ${filePath}`)
    return
  }

  // Generate template
  const content = generatePRDTemplate(taskId, taskInfo.title)

  // Create file
  await createPRDFile(filePath, content)

  logger.success(`Auto-created PRD file: ${filePath}`)
  logger.info('Please review and update the PRD with actual requirements')
}
