/**
 * Create PRD Action Tests
 * Tests for auto-creating PRD files with task metadata from tasks.json
 */

import { describe, test, expect, beforeEach, afterEach } from 'bun:test'
import fs from 'fs'
import path from 'path'
import os from 'os'
import { generatePRDTemplate, createPRDFile, executeCreatePRD, extractTaskInfo } from '../src/actions/create-prd'
import type { AutoFixAction } from '../src/actions'

describe('Create PRD Action', () => {
  let TEST_DIR: string
  let TEST_TASKS_DIR: string

  beforeEach(() => {
    // Create unique temp directory for each test
    TEST_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'test-prd-'))
    TEST_TASKS_DIR = path.join(TEST_DIR, '.specs', 'tasks')
    fs.mkdirSync(TEST_TASKS_DIR, { recursive: true })
  })

  afterEach(() => {
    if (fs.existsSync(TEST_DIR)) {
      fs.rmSync(TEST_DIR, { recursive: true })
    }
  })

  describe('extractTaskInfo', () => {
    test('should extract task ID from PRD path', () => {
      const context = {
        path: '.specs/tasks/TASK-001.md'
      }

      const result = extractTaskInfo(context)

      expect(result).toBeDefined()
      expect(result?.taskId).toBe('TASK-001')
      expect(result?.path).toBe('.specs/tasks/TASK-001.md')
    })

    test('should extract task ID with lowercase letter suffix', () => {
      const context = {
        path: '.specs/tasks/TASK-001a.md'
      }

      const result = extractTaskInfo(context)

      expect(result).toBeDefined()
      expect(result?.taskId).toBe('TASK-001a')
    })

    test('should extract task ID with multi-word prefix', () => {
      const context = {
        path: '.specs/tasks/AI-MONITOR-001d.md'
      }

      const result = extractTaskInfo(context)

      expect(result).toBeDefined()
      expect(result?.taskId).toBe('AI-MONITOR-001d')
    })

    test('should return null for invalid path', () => {
      const context = {
        path: '.specs/invalid-file.md'
      }

      const result = extractTaskInfo(context)

      expect(result).toBeNull()
    })

    test('should return null for missing path', () => {
      const context = {}

      const result = extractTaskInfo(context)

      expect(result).toBeNull()
    })
  })

  describe('generatePRDTemplate', () => {
    test('should generate template with taskId only', () => {
      const content = generatePRDTemplate('TASK-001')

      expect(content).toContain('# TASK-001: TASK-001')
      expect(content).toContain('## Goal')
      expect(content).toContain('## Requirements')
      expect(content).toContain('[Auto-generated stub - please fill in goal]')
    })

    test('should generate template with title', () => {
      const content = generatePRDTemplate('TASK-001', 'My Task Title')

      expect(content).toContain('# TASK-001: My Task Title')
      expect(content).toContain('## Goal')
      expect(content).toContain('[Auto-generated stub - please fill in goal]')
    })

    test('should generate template with title and description', () => {
      const description = 'This is a detailed description of what needs to be done'
      const content = generatePRDTemplate('TASK-001', 'My Task', description)

      expect(content).toContain('# TASK-001: My Task')
      expect(content).toContain('## Goal')
      expect(content).toContain('This is a detailed description of what needs to be done')
      expect(content).not.toContain('[Auto-generated stub')
    })

    test('should include implementation notes and references sections', () => {
      const content = generatePRDTemplate('TASK-001')

      expect(content).toContain('## Implementation Notes')
      expect(content).toContain('## References')
      expect(content).toContain('*Auto-generated by Loopwork AI Monitor*')
    })
  })

  describe('createPRDFile', () => {
    test('should create PRD file with content', async () => {
      const filePath = path.join(TEST_TASKS_DIR, 'TEST-001.md')
      const content = '# Test PRD\n\n## Goal\nTest goal'

      await createPRDFile(filePath, content)

      expect(fs.existsSync(filePath)).toBe(true)
      const fileContent = fs.readFileSync(filePath, 'utf8')
      expect(fileContent).toBe(content)
    })

    test('should create parent directories if they do not exist', async () => {
      const filePath = path.join(TEST_DIR, 'a', 'b', 'c', 'TEST-001.md')
      const content = '# Test PRD'

      await createPRDFile(filePath, content)

      expect(fs.existsSync(filePath)).toBe(true)
      expect(fs.existsSync(path.dirname(filePath))).toBe(true)
    })
  })

  describe('executeCreatePRD', () => {
    test('should create PRD file from stub template when no metadata found', async () => {
      const taskId = 'TEST-001'
      const filePath = path.join(TEST_TASKS_DIR, `${taskId}.md`)

      const action: AutoFixAction = {
        type: 'auto-fix',
        pattern: 'prd-not-found',
        context: {
          path: path.relative(TEST_DIR, filePath)
        },
        fn: async () => {}
      }

      await executeCreatePRD(action, TEST_DIR)

      expect(fs.existsSync(filePath)).toBe(true)
      const content = fs.readFileSync(filePath, 'utf8')
      expect(content).toContain('# TEST-001: TEST-001')
      expect(content).toContain('[Auto-generated stub')
    })

    test('should create PRD file with metadata from tasks.json', async () => {
      const taskId = 'META-001'
      const tasksJson = path.join(TEST_TASKS_DIR, 'tasks.json')
      const filePath = path.join(TEST_TASKS_DIR, `${taskId}.md`)

      // Create tasks.json with metadata
      const tasksData = {
        tasks: [
          {
            id: taskId,
            title: 'My Important Task',
            description: 'This is a detailed description of the task to be completed'
          }
        ]
      }
      fs.writeFileSync(tasksJson, JSON.stringify(tasksData, null, 2))

      const action: AutoFixAction = {
        type: 'auto-fix',
        pattern: 'prd-not-found',
        context: {
          path: path.relative(TEST_DIR, filePath)
        },
        fn: async () => {}
      }

      await executeCreatePRD(action, TEST_DIR)

      expect(fs.existsSync(filePath)).toBe(true)
      const content = fs.readFileSync(filePath, 'utf8')
      expect(content).toContain('# META-001: My Important Task')
      expect(content).toContain('This is a detailed description of the task to be completed')
      expect(content).not.toContain('[Auto-generated stub')
    })

    test('should handle case-insensitive task ID lookup', async () => {
      const taskId = 'case-001'
      const tasksJson = path.join(TEST_TASKS_DIR, 'tasks.json')
      const filePath = path.join(TEST_TASKS_DIR, `${taskId}.md`)

      // Create tasks.json with uppercase task ID
      const tasksData = {
        tasks: [
          {
            id: 'CASE-001',
            title: 'Case Sensitive Test',
            description: 'Testing case-insensitive lookup'
          }
        ]
      }
      fs.writeFileSync(tasksJson, JSON.stringify(tasksData, null, 2))

      const action: AutoFixAction = {
        type: 'auto-fix',
        pattern: 'prd-not-found',
        context: {
          path: path.relative(TEST_DIR, filePath)
        },
        fn: async () => {}
      }

      await executeCreatePRD(action, TEST_DIR)

      expect(fs.existsSync(filePath)).toBe(true)
      const content = fs.readFileSync(filePath, 'utf8')
      expect(content).toContain('Case Sensitive Test')
      expect(content).toContain('Testing case-insensitive lookup')
    })

    test('should not overwrite existing PRD file', async () => {
      const taskId = 'EXIST-001'
      const filePath = path.join(TEST_TASKS_DIR, `${taskId}.md`)

      // Create existing PRD file
      const existingContent = '# Existing PRD\n\nThis should not be overwritten'
      fs.writeFileSync(filePath, existingContent)

      const action: AutoFixAction = {
        type: 'auto-fix',
        pattern: 'prd-not-found',
        context: {
          path: path.relative(TEST_DIR, filePath)
        },
        fn: async () => {}
      }

      await executeCreatePRD(action, TEST_DIR)

      // File should still contain original content
      const content = fs.readFileSync(filePath, 'utf8')
      expect(content).toBe(existingContent)
    })

    test('should handle missing tasks.json gracefully', async () => {
      const taskId = 'NOMETA-001'
      const filePath = path.join(TEST_TASKS_DIR, `${taskId}.md`)

      // Don't create tasks.json, just use stub
      const action: AutoFixAction = {
        type: 'auto-fix',
        pattern: 'prd-not-found',
        context: {
          path: path.relative(TEST_DIR, filePath)
        },
        fn: async () => {}
      }

      await executeCreatePRD(action, TEST_DIR)

      expect(fs.existsSync(filePath)).toBe(true)
      const content = fs.readFileSync(filePath, 'utf8')
      expect(content).toContain('# NOMETA-001: NOMETA-001')
      expect(content).toContain('[Auto-generated stub')
    })

    test('should handle task not found in tasks.json gracefully', async () => {
      const taskId = 'NOTFOUND-001'
      const tasksJson = path.join(TEST_TASKS_DIR, 'tasks.json')
      const filePath = path.join(TEST_TASKS_DIR, `${taskId}.md`)

      // Create tasks.json with different task
      const tasksData = {
        tasks: [
          {
            id: 'OTHER-001',
            title: 'Other Task',
            description: 'Different task'
          }
        ]
      }
      fs.writeFileSync(tasksJson, JSON.stringify(tasksData, null, 2))

      const action: AutoFixAction = {
        type: 'auto-fix',
        pattern: 'prd-not-found',
        context: {
          path: path.relative(TEST_DIR, filePath)
        },
        fn: async () => {}
      }

      await executeCreatePRD(action, TEST_DIR)

      expect(fs.existsSync(filePath)).toBe(true)
      const content = fs.readFileSync(filePath, 'utf8')
      // Should fall back to stub when task not found
      expect(content).toContain('# NOTFOUND-001: NOTFOUND-001')
      expect(content).toContain('[Auto-generated stub')
    })

    test('should handle tasks.json with direct array format', async () => {
      const taskId = 'ARRAY-001'
      const tasksJson = path.join(TEST_TASKS_DIR, 'tasks.json')
      const filePath = path.join(TEST_TASKS_DIR, `${taskId}.md`)

      // Create tasks.json with direct array (not wrapped in object)
      const tasksData = [
        {
          id: taskId,
          title: 'Array Format Task',
          description: 'Testing direct array format in tasks.json'
        }
      ]
      fs.writeFileSync(tasksJson, JSON.stringify(tasksData, null, 2))

      const action: AutoFixAction = {
        type: 'auto-fix',
        pattern: 'prd-not-found',
        context: {
          path: path.relative(TEST_DIR, filePath)
        },
        fn: async () => {}
      }

      await executeCreatePRD(action, TEST_DIR)

      expect(fs.existsSync(filePath)).toBe(true)
      const content = fs.readFileSync(filePath, 'utf8')
      expect(content).toContain('Array Format Task')
      expect(content).toContain('Testing direct array format')
    })
  })
})
