/**
 * Auto-create missing PRD files
 *
 * When a task is started but its PRD file doesn't exist,
 * this action generates a stub PRD with a basic template.
 *
 * Task metadata is read from .specs/tasks/tasks.json to populate
 * the PRD with accurate title and description from the task registry.
 */

import fs from 'fs'
import path from 'path'
import { logger } from '../utils'
import type { Action } from './index'

export interface CreatePRDContext {
  taskId: string
  title?: string
  description?: string
  path?: string
}

export interface TaskMetadata {
  id: string
  title: string
  description?: string
  [key: string]: unknown
}

/**
 * Read task metadata from tasks.json
 */
function readTaskMetadata(tasksFilePath: string, taskId: string): TaskMetadata | null {
  try {
    if (!fs.existsSync(tasksFilePath)) {
      logger.debug(`Tasks file not found: ${tasksFilePath}`)
      return null
    }

    const content = fs.readFileSync(tasksFilePath, 'utf8')
    const data = JSON.parse(content)

    // Support both { tasks: [...] } and direct array format
    const tasksList = Array.isArray(data) ? data : data.tasks || []

    // Find task by ID (case-insensitive match)
    const task = tasksList.find(
      (t: Record<string, unknown>) =>
        typeof t.id === 'string' && t.id.toUpperCase() === taskId.toUpperCase()
    )

    if (!task) {
      logger.debug(`Task not found in tasks.json: ${taskId}`)
      return null
    }

    return {
      id: task.id as string,
      title: (task.title as string) || taskId,
      description: (task.description as string) || undefined
    }
  } catch (error) {
    logger.debug(`Error reading task metadata: ${error instanceof Error ? error.message : String(error)}`)
    return null
  }
}

/**
 * Extract task ID from PRD not found error message
 */
export function extractTaskInfo(context: Record<string, string>): CreatePRDContext | null {
  const prdPath = context.path

  if (!prdPath) {
    logger.debug('No PRD path found in context')
    return null
  }

  // Extract task ID from path: .specs/tasks/TASK-001.md -> TASK-001
  // Also handles multi-word prefixes: AI-MONITOR-001d
  const match = prdPath.match(/([A-Z]+(?:-[A-Z]+)*-\d+[a-z]?)\.md$/i)
  if (!match) {
    logger.debug(`Could not extract task ID from path: ${prdPath}`)
    return null
  }

  const taskId = match[1]
  return {
    taskId,
    path: prdPath
  }
}

/**
 * Generate PRD template content with task metadata
 */
export function generatePRDTemplate(taskId: string, title?: string, description?: string): string {
  const taskTitle = title || taskId
  const goalSection = description
    ? `## Goal\n${description}`
    : `## Goal\n[Auto-generated stub - please fill in goal]\n\nThis task was started without a detailed specification.`

  return `# ${taskId}: ${taskTitle}

${goalSection}

## Requirements
- [ ] Define specific requirements
- [ ] Add acceptance criteria
- [ ] Specify constraints or dependencies

## Implementation Notes
Please review and update this PRD with:
- Clear, measurable requirements
- Expected outcomes
- Any technical constraints
- Dependencies on other tasks

## References
- Related tasks: (list any related task IDs)
- Documentation: (links to relevant docs)

---
*Auto-generated by Loopwork AI Monitor*
`
}

/**
 * Create PRD file at specified path
 */
export async function createPRDFile(filePath: string, content: string): Promise<void> {
  const dir = path.dirname(filePath)

  // Create directory if it doesn't exist
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
    logger.debug(`Created directory: ${dir}`)
  }

  // Write PRD file
  fs.writeFileSync(filePath, content, 'utf8')
  logger.debug(`Created PRD file: ${filePath}`)
}

/**
 * Execute auto-create PRD action
 */
export async function executeCreatePRD(action: Action, projectRoot?: string): Promise<void> {
  const taskInfo = extractTaskInfo(action.context)

  if (!taskInfo) {
    throw new Error('Could not extract task information from error context')
  }

  const { taskId, path: prdPath } = taskInfo
  const root = projectRoot || process.cwd()

  // Determine PRD file path
  // If prdPath is provided from context, it's relative to project root
  const filePath = prdPath
    ? (path.isAbsolute(prdPath) ? prdPath : path.join(root, prdPath))
    : path.join(root, '.specs', 'tasks', `${taskId}.md`)

  // Check if file already exists (race condition protection)
  if (fs.existsSync(filePath)) {
    logger.info(`PRD file already exists: ${filePath}`)
    return
  }

  // Try to read task metadata from tasks.json
  const tasksJsonPath = path.join(root, '.specs', 'tasks', 'tasks.json')
  const taskMetadata = readTaskMetadata(tasksJsonPath, taskId)

  // Generate template with metadata (falls back to taskId if metadata not found)
  const content = generatePRDTemplate(
    taskId,
    taskMetadata?.title || taskInfo.title,
    taskMetadata?.description
  )

  // Create file
  await createPRDFile(filePath, content)

  const metadataSource = taskMetadata ? ' (with metadata from tasks.json)' : ''
  logger.success(`Auto-created PRD file: ${filePath}${metadataSource}`)
  logger.info('Please review and update the PRD with actual requirements')
}
